/*
 * Copyright (c) 2026, Park, Sungchul All rights reserved.
 *
 * This source code is licensed under the BSD-style license found in the LICENSE file in the root
 * directory of this source tree.
 */

package com.fupfin.midiraja.midi.vgm;

import java.util.List;
import java.util.Optional;
import java.util.concurrent.CopyOnWriteArrayList;
import java.util.concurrent.StructuredTaskScope;
import java.util.concurrent.atomic.AtomicBoolean;
import java.util.concurrent.atomic.AtomicLong;
import java.util.concurrent.atomic.AtomicReference;
import java.util.function.Consumer;
import javax.sound.midi.Sequence;

import com.fupfin.midiraja.dsp.SpectrumAnalyzerFilter;
import com.fupfin.midiraja.engine.PlaybackEngine;
import com.fupfin.midiraja.engine.PlaylistContext;
import com.fupfin.midiraja.ui.PlaybackEventListener;
import com.fupfin.midiraja.ui.PlaybackUI;

/**
 * Drives playback for {@link LibvgmSynthProvider}.
 *
 * <p>
 * Unlike {@link com.fupfin.midiraja.engine.MidiPlaybackEngine}, audio is generated by libvgm's own
 * render thread (started by {@link LibvgmSynthProvider#loadVgmFile} or
 * {@link LibvgmSynthProvider#loadVgmData}). This engine only manages the UI lifecycle and tracks
 * wall-clock progress while polling {@link LibvgmSynthProvider#isDone()}.
 */
public class LibvgmPlaybackEngine implements PlaybackEngine
{
    private static final int STARTUP_DELAY_MS = 500;
    private static final int POLL_MS = 50;

    private final LibvgmSynthProvider provider;
    private final Sequence sequence;
    private final PlaylistContext context;

    private final AtomicBoolean isPlaying = new AtomicBoolean(false);
    private final AtomicBoolean isPaused = new AtomicBoolean(false);
    private final AtomicLong currentMicroseconds = new AtomicLong(0);
    private final AtomicReference<PlaybackStatus> endStatus = new AtomicReference<>(
            PlaybackStatus.FINISHED);
    private final List<PlaybackEventListener> listeners = new CopyOnWriteArrayList<>();

    private volatile double currentSpeed = 1.0;

    /**
     * Seek synchronisation: when seekRelative() fires, these two atomics let playLoop() rebuild
     * its wall-clock base so that currentMicroseconds stays consistent after the seek.
     * seekEpochMs == -1 means "no pending seek".
     */
    private final AtomicLong seekEpochMs = new AtomicLong(-1);
    private final AtomicLong seekTargetUs = new AtomicLong(0);

    private volatile boolean holdAtEnd = false;
    private volatile boolean bookmarked = false;
    private volatile String filterDescription = "";
    private volatile String portSuffix = "";
    private volatile String chipSuffix = "";

    @SuppressWarnings("NullAway")
    private volatile Consumer<Boolean> bookmarkCallback = null;
    @SuppressWarnings("NullAway")
    private volatile Consumer<Boolean> shuffleCallback = null;
    @SuppressWarnings("NullAway")
    private volatile SpectrumAnalyzerFilter spectrumFilter = null;

    public LibvgmPlaybackEngine(Sequence sequence, LibvgmSynthProvider provider,
            PlaylistContext context)
    {
        this.sequence = sequence;
        this.provider = provider;
        this.context = context;
    }

    // ── PlaybackEngine lifecycle ──────────────────────────────────────────────

    @Override
    public PlaybackStatus start(PlaybackUI ui) throws Exception
    {
        isPlaying.set(true);
        endStatus.set(PlaybackStatus.FINISHED);

        try (var scope = StructuredTaskScope.open())
        {
            scope.fork(() -> runRenderLoopTask(ui));
            scope.fork(() -> runInputLoopTask(ui));

            playLoop();
            isPlaying.set(false);

            scope.join();
        }

        var status = endStatus.get();
        return status != null ? status : PlaybackStatus.FINISHED;
    }

    @Override
    public void setHoldAtEnd(boolean hold)
    {
        this.holdAtEnd = hold;
    }

    @Override
    public void setIgnoreSysex(boolean ignoreSysex)
    {
        // no-op: libvgm does not process SysEx
    }

    @Override
    public void setInitialResetType(Optional<String> resetType)
    {
        // no-op
    }

    @Override
    public void setInitiallyPaused()
    {
        isPaused.set(true);
    }

    @Override
    public void setFilterDescription(String desc)
    {
        this.filterDescription = desc;
    }

    @Override
    public void setPortSuffix(String suffix)
    {
        this.portSuffix = suffix;
    }

    @Override
    public void setBookmarked(boolean bookmarked)
    {
        this.bookmarked = bookmarked;
    }

    @Override
    public void setBookmarkCallback(Consumer<Boolean> callback)
    {
        this.bookmarkCallback = callback;
    }

    @Override
    public void setShuffleCallback(Consumer<Boolean> callback)
    {
        this.shuffleCallback = callback;
    }

    public void setSpectrumFilter(SpectrumAnalyzerFilter filter)
    {
        this.spectrumFilter = filter;
    }

    public void setChipSuffix(String suffix)
    {
        this.chipSuffix = suffix;
    }

    // ── PlaybackState ─────────────────────────────────────────────────────────

    @Override
    public PlaylistContext getContext()
    {
        return context;
    }

    @Override
    public Sequence getSequence()
    {
        return sequence;
    }

    @Override
    public long getCurrentMicroseconds()
    {
        return currentMicroseconds.get();
    }

    @Override
    public long getTotalMicroseconds()
    {
        long seqUs = sequence.getMicrosecondLength();
        return seqUs > 0 ? seqUs : provider.getDurationMicroseconds();
    }

    @Override
    public int[] getChannelPrograms()
    {
        return new int[16];
    }

    @Override
    public float getCurrentBpm()
    {
        return 120.0f;
    }

    @Override
    public double getCurrentSpeed()
    {
        return currentSpeed;
    }

    @Override
    public int getCurrentTranspose()
    {
        return 0;
    }

    @Override
    public double getVolumeScale()
    {
        return provider.getVolumeScale();
    }

    @Override
    public boolean isPlaying()
    {
        return isPlaying.get();
    }

    @Override
    public boolean isPaused()
    {
        return isPaused.get();
    }

    @Override
    public boolean isLoopEnabled()
    {
        return false;
    }

    @Override
    public boolean isShuffleEnabled()
    {
        return false;
    }

    @Override
    public boolean isBookmarked()
    {
        return bookmarked;
    }

    @Override
    public String getFilterDescription()
    {
        return filterDescription;
    }

    @Override
    public String getPortSuffix()
    {
        return chipSuffix + portSuffix;
    }

    @Override
    public boolean isSpectrumMode()
    {
        return spectrumFilter != null;
    }

    @Override
    public void addPlaybackEventListener(PlaybackEventListener listener)
    {
        listeners.add(listener);
    }

    // ── PlaybackCommands ──────────────────────────────────────────────────────

    @Override
    public void requestStop(PlaybackStatus status)
    {
        endStatus.set(status);
        isPlaying.set(false);
    }

    @Override
    public void adjustVolume(double delta)
    {
        float newScale = (float) Math.max(0.0, Math.min(1.0, provider.getVolumeScale() + delta));
        provider.setVolumeScale(newScale);
        listeners.forEach(PlaybackEventListener::onPlaybackStateChanged);
    }

    @Override
    public void adjustSpeed(double delta)
    {
        currentSpeed = Math.max(0.1, Math.min(4.0, currentSpeed + delta));
        provider.setSpeed(currentSpeed);
        listeners.forEach(PlaybackEventListener::onPlaybackStateChanged);
    }

    @Override
    public boolean isTransposeSupported()
    {
        return false;
    }

    @Override
    public void adjustTranspose(int delta)
    {
        // not supported: VGM files contain pre-recorded chip register writes with baked-in
        // frequencies; there is no pitch-shift API in libvgm's PlayerA.
    }

    @Override
    public void seekRelative(long microsecondsDelta)
    {
        long total = getTotalMicroseconds();
        long target = currentMicroseconds.get() + microsecondsDelta;
        target = Math.max(0, target);
        if (total > 0)
            target = Math.min(target, total);
        provider.seekTo(target);
        currentMicroseconds.set(target);
        // Tell playLoop() to rebuild its wall-clock base from this new position.
        seekTargetUs.set(target);
        seekEpochMs.set(System.currentTimeMillis());
        long finalTarget = target;
        listeners.forEach(l -> l.onTick(finalTarget));
    }

    @Override
    public void togglePause()
    {
        boolean prev;
        do
        {
            prev = isPaused.get();
        }
        while (!isPaused.compareAndSet(prev, !prev));

        if (!prev)
            provider.pauseRender();
        else
            provider.resumeRender();

        listeners.forEach(PlaybackEventListener::onPlaybackStateChanged);
    }

    @Override
    public void toggleLoop()
    {
        // no-op
    }

    @Override
    public void toggleShuffle()
    {
        // no-op
    }

    @Override
    public void fireBookmark()
    {
        bookmarked = !bookmarked;
        var cb = bookmarkCallback;
        if (cb != null)
            cb.accept(bookmarked);
        listeners.forEach(l -> l.onBookmarkChanged(bookmarked));
    }

    @Override
    public void firePlayOrderChanged(PlaylistContext ctx)
    {
        // no-op
    }

    // ── Internal play loop ────────────────────────────────────────────────────

    private void fireSpectrumLevels()
    {
        if (spectrumFilter == null)
            return;
        float[] lv = spectrumFilter.getLevels();
        listeners.forEach(l -> l.onSpectrumUpdate(lv));
    }

    private Boolean runRenderLoopTask(PlaybackUI ui) throws Exception
    {
        ui.runRenderLoop(this);
        return Boolean.TRUE;
    }

    private Boolean runInputLoopTask(PlaybackUI ui) throws Exception
    {
        ui.runInputLoop(this);
        return Boolean.TRUE;
    }

    @SuppressWarnings("EmptyCatch")
    private void playLoop() throws InterruptedException
    {
        // Startup delay: lets rapid NEXT/PREV skip without producing audio
        long endNs = System.nanoTime() + STARTUP_DELAY_MS * 1_000_000L;
        while (System.nanoTime() < endNs && isPlaying.get())
            Thread.sleep(10);

        if (!isPlaying.get())
            return;

        // Honour setInitiallyPaused()
        while (isPaused.get() && isPlaying.get())
            Thread.sleep(POLL_MS);

        if (!isPlaying.get())
            return;

        provider.resumeRender();

        long startMs = System.currentTimeMillis();
        long pausedMs = 0;
        long pauseStartMs = 0;
        boolean wasPaused = false;
        // Known duration from MIDI sequence or libvgm; 0 means truly unknown
        long totalUs = getTotalMicroseconds();

        while (isPlaying.get() && !provider.isDone())
        {
            // Apply any pending seek: rebuild startMs so elapsed = seekTarget going forward.
            long epoch = seekEpochMs.getAndSet(-1);
            if (epoch >= 0)
            {
                long seekedUs = seekTargetUs.get();
                // If we were mid-pause-tracking, fold the partial pause into pausedMs first.
                if (wasPaused)
                {
                    pausedMs += epoch - pauseStartMs;
                    pauseStartMs = epoch;
                }
                // Rebase: choose startMs so that (epoch - startMs - pausedMs) * 1000 == seekedUs
                startMs = epoch - pausedMs - seekedUs / 1000L;
            }

            boolean curPaused = isPaused.get();

            if (curPaused && !wasPaused)
            {
                pauseStartMs = System.currentTimeMillis();
                wasPaused = true;
            }
            else if (!curPaused && wasPaused)
            {
                pausedMs += System.currentTimeMillis() - pauseStartMs;
                wasPaused = false;
            }

            if (!curPaused)
            {
                long elapsed = (System.currentTimeMillis() - startMs - pausedMs) * 1000L;
                currentMicroseconds.set(elapsed);
                long us = elapsed;
                listeners.forEach(l -> l.onTick(us));
                fireSpectrumLevels();
            }

            // For MIDI-derived VGM the sequence duration is known; exit when time is up
            // even if the VGM has loop points that prevent isDone() from firing.
            if (totalUs > 0 && currentMicroseconds.get() >= totalUs)
                break;

            Thread.sleep(POLL_MS);
        }

        if (!isPlaying.get())
            return;

        // Track finished naturally — broadcast final position
        long total = getTotalMicroseconds();
        if (total > 0)
            currentMicroseconds.set(total);
        long us = currentMicroseconds.get();
        listeners.forEach(l -> l.onTick(us));

        try
        {
            Thread.sleep(20);
        }
        catch (InterruptedException _)
        {}

        if (holdAtEnd)
        {
            while (isPlaying.get() && endStatus.get() == PlaybackStatus.FINISHED)
                Thread.sleep(POLL_MS);
        }
    }
}
