/*
 * Copyright (c) 2026, Park, Sungchul All rights reserved.
 *
 * This source code is licensed under the BSD-style license found in the LICENSE file in the root
 * directory of this source tree.
 */

package com.fupfin.midiraja.export.vgm;

import java.util.Arrays;

/**
 * {@link ChipHandler} for OKI MSM6258 (OKIM6258) — PCM percussion-only chip.
 *
 * <p>
 * The MSM6258 has no internal ROM; it streams 4-bit OKI ADPCM data via the VGM DAC stream
 * mechanism. Seven synthetic drum samples (generated by {@link OkiAdpcmCodec}) are embedded as
 * PCM data blocks (type 0x04) at {@link #initSilence} time, then triggered individually via
 * DAC stream play-block commands (0x95) on each percussion hit.
 *
 * <p>
 * This handler provides no melodic slots ({@link #slotCount()} = 0) and uses a single DAC
 * stream (stream ID 0) for all percussion playback.
 */
final class Msm6258Handler implements ChipHandler
{
    private static final int STREAM_ID = 0;
    /** VGM chip-type byte for OKIM6258 in the DAC stream setup command. */
    private static final int VGM_CHIP_OKIM6258 = 0x17;
    /** PCM bank type for OKIM6258 data blocks (VGM PCM block type 0x04). */
    private static final int PCM_BANK_OKIM6258 = 0x04;

    /**
     * GM percussion note → drum sample index (0-6), or -1 if not mapped.
     * Array is indexed by MIDI note number (0-127).
     */
    private static final int[] NOTE_TO_DRUM = buildNoteMap();

    /** Pre-encoded OKI ADPCM bytes for each of the 7 drum types. */
    private static final byte[][] DRUM_SAMPLES = OkiAdpcmCodec.generateDrumSamples();

    @Override
    public ChipType chipType()
    {
        return ChipType.MSM6258;
    }

    @Override
    public int slotCount()
    {
        return 0; // percussion-only chip; no melodic slots
    }

    @Override
    public int percussionPriority()
    {
        return 3; // PCM > FM (2) > PSG noise (1)
    }

    /**
     * Writes 7 PCM data blocks, then sets up and configures the DAC stream.
     *
     * <p>
     * Block indices correspond directly to drum types (0=bass drum, 1=snare, …, 6=open hi-hat).
     */
    @Override
    public void initSilence(VgmWriter w)
    {
        // Embed all 7 drum samples as PCM data blocks (block index = drum type index)
        for (byte[] sample : DRUM_SAMPLES)
            w.writePcmDataBlock(PCM_BANK_OKIM6258, sample);

        // Stop any previously running stream
        w.writeDacStreamStop(STREAM_ID);

        // Setup: stream 0 → OKIM6258, port 0, register 0x01
        w.writeDacStreamSetup(STREAM_ID, VGM_CHIP_OKIM6258, 0x00, 0x01);

        // Assign PCM bank type, stepSize=1 (one packed byte per step), stepBase=0x00 (no offset)
        w.writeDacStreamData(STREAM_ID, PCM_BANK_OKIM6258, 0x01, 0x00);

        // Set playback frequency: 15,625 Hz (8 MHz / 512)
        w.writeDacStreamFrequency(STREAM_ID, VgmWriter.MSM6258_SAMPLE_RATE);

        // Start ADPCM decoder: without COMMAND_PLAY the chip stays silent (STATUS_PLAYING=0)
        w.writeMsm6258(0x00, 0x02);
    }

    @Override
    public void startNote(int localSlot, int note, int velocity, int program, VgmWriter w)
    {
        // No melodic slots — never called
    }

    @Override
    public void silenceSlot(int localSlot, VgmWriter w)
    {
        // No melodic slots — never called
    }

    @Override
    public void handlePercussion(int note, int velocity, VgmWriter w)
    {
        if (velocity == 0)
        {
            w.writeDacStreamStop(STREAM_ID);
            return;
        }
        int drumIdx = note >= 0 && note < NOTE_TO_DRUM.length ? NOTE_TO_DRUM[note] : -1;
        if (drumIdx < 0)
            return; // unmapped GM percussion note — ignore
        // Reset ADPCM decoder state to (signal=-2, step=0) before each hit.
        // OkiAdpcmCodec.encode() assumes this exact initial state; a mismatch caused by a
        // previous sample's leftover state produces a brief onset artifact.
        w.writeDacStreamStop(STREAM_ID);
        w.writeMsm6258(0x00, 0x00); // STOP: resets signal=-2, step=0 (MAME/libvgm okim6258.c)
        w.writeMsm6258(0x00, 0x02); // PLAY: arm decoder for incoming data
        w.writeDacStreamPlayBlock(STREAM_ID, drumIdx, 0x00);
    }

    @Override
    public void finalSilence(VgmWriter w)
    {
        w.writeDacStreamStop(STREAM_ID);
    }

    // ── Note map builder ──────────────────────────────────────────────────────

    private static int[] buildNoteMap()
    {
        int[] map = new int[128];
        Arrays.fill(map, -1);

        // 0 = Bass drum (GM 35, 36)
        map[35] = 0;
        map[36] = 0;

        // 1 = Snare (GM 38, 40)
        map[38] = 1;
        map[40] = 1;

        // 2 = Crash / cymbal (GM 49, 51, 52, 53, 55, 57, 59)
        for (int n : new int[] { 49, 51, 52, 53, 55, 57, 59 })
            map[n] = 2;

        // 3 = Closed hi-hat (GM 42, 44)
        map[42] = 3;
        map[44] = 3;

        // 4 = Tom (GM 41, 43, 45, 47, 48, 50)
        for (int n : new int[] { 41, 43, 45, 47, 48, 50 })
            map[n] = 4;

        // 5 = Rim shot (GM 37, 39)
        map[37] = 5;
        map[39] = 5;

        // 6 = Open hi-hat (GM 46)
        map[46] = 6;

        return map;
    }
}
