/*
 * Copyright (c) 2026, Park, Sungchul All rights reserved.
 *
 * This source code is licensed under the BSD-style license found in the LICENSE file in the root
 * directory of this source tree.
 */

package com.fupfin.midiraja.export.vgm;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;

/**
 * Parses OPM GM bank files ({@code opm_gm.bin}) and provides YM2151 (OPM) patch data.
 *
 * <p>
 * The OPM bank is generated by {@code scripts/gen_opm_bank.py} using Differential Evolution
 * with FluidR3_GM.sf3 as reference audio. Unlike WOPN2 (which has no DT2 field), each operator
 * in this format carries a {@code dt2d2r} byte that encodes both the OPM-exclusive DT2 parameter
 * (bits 7-6) and the D2R rate (bits 4-0).
 *
 * <p>
 * File format:
 * <ul>
 *   <li>Header: magic {@code OPMGM-BNK\0} (10 bytes) + version u8 + nMelodic u16le + nPercussion u16le
 *   <li>128 melodic patches + 128 percussion patches
 *   <li>Each patch: 52 bytes — name[16] + noteOffset(i8) + percKey(u8) + fbalg(u8) + lfosens(u8)
 *       + 4 × operator(8 bytes: dt1mul, tl, ksatk, amd1r, dt2d2r, d1lrr, ssgeg, _pad)
 * </ul>
 */
public final class OpmBankReader
{
    private static final byte[] MAGIC = "OPMGM-BNK\0".getBytes();
    private static final int HEADER_SIZE = 15; // 10 magic + 1 version + 2 nMelodic + 2 nPercussion
    private static final int PATCH_BYTES = 52; // name[16] + 4 fields(1 each) + 4×op(8 bytes)
    private static final int OP_SIZE = 8;
    private static final int OP_OFFSET = 20; // offset of first operator within a patch

    /**
     * YM2151 operator parameters for one operator.
     *
     * @param dt1mul  register 0x40+: bits 6-4 = DT1, bits 3-0 = MUL
     * @param tl      register 0x60+: total level, 0-127 (0 = loudest)
     * @param ksatk   register 0x80+: bits 7-6 = KS, bits 4-0 = AR
     * @param amd1r   register 0xA0+: bit 7 = AM-EN, bits 4-0 = D1R
     * @param dt2d2r  register 0xC0+: bits 7-6 = DT2, bits 4-0 = D2R  (OPM-exclusive DT2)
     * @param d1lrr   register 0xE0+: bits 7-4 = D1L, bits 3-0 = RR
     */
    public record Operator(int dt1mul, int tl, int ksatk, int amd1r, int dt2d2r, int d1lrr)
    {
    }

    /**
     * OPM FM patch data for one instrument (4-operator voice).
     *
     * @param name       Instrument name
     * @param noteOffset Semitone transposition to apply on playback
     * @param percKey    Percussion key number (0 for melodic patches)
     * @param fbalg      Feedback and algorithm: bits 5-3 = FB, bits 2-0 = ALG
     * @param lfosens    LFO sensitivity: bits 6-4 = PMS, bits 1-0 = AMS
     * @param operators  Four operators in OPM slot order: [S1, S3, S2, S4]
     */
    public record Patch(String name, int noteOffset, int percKey, int fbalg, int lfosens,
            Operator[] operators)
    {
    }

    private final Patch[] melodicPatches;
    private final Patch[] percussionPatches;

    private OpmBankReader()
    {
        melodicPatches = new Patch[128];
        percussionPatches = new Patch[128];
    }

    private OpmBankReader(byte[] data) throws IOException
    {
        melodicPatches = new Patch[128];
        percussionPatches = new Patch[128];
        parse(data);
    }

    /**
     * Load an OPM GM bank file.
     *
     * @param path path to {@code opm_gm.bin}
     * @return populated reader
     * @throws IOException if the file cannot be read or is not a valid OPM bank
     */
    public static OpmBankReader load(Path path) throws IOException
    {
        return new OpmBankReader(Files.readAllBytes(path));
    }

    /**
     * Load an OPM GM bank from a raw byte array.
     *
     * @param data raw bytes of {@code opm_gm.bin}
     * @return populated reader
     * @throws IOException if the data is not a valid OPM bank
     */
    public static OpmBankReader load(byte[] data) throws IOException
    {
        return new OpmBankReader(data);
    }

    /**
     * Build an {@link OpmBankReader} by converting a {@link WopnBankReader} bank.
     *
     * <p>
     * Used as a fallback when {@code opm_gm.bin} has not been generated yet. All DT2 values
     * are set to zero (the WOPN format has no DT2 field). Once {@code opm_gm.bin} is generated
     * by {@code scripts/gen_opm_bank.py}, the richer OPM bank will be loaded instead.
     *
     * @param wopn source WOPN bank
     * @return reader whose patches mirror the WOPN data with DT2=0
     */
    public static OpmBankReader fromWopn(WopnBankReader wopn)
    {
        OpmBankReader r = new OpmBankReader();
        for (int i = 0; i < 128; i++)
        {
            try
            {
                r.melodicPatches[i] = convertWopnPatch(wopn.melodicPatch(i));
            }
            catch (IllegalArgumentException ignored)
            {
            }
            try
            {
                r.percussionPatches[i] = convertWopnPatch(wopn.percussionPatch(i));
            }
            catch (IllegalArgumentException ignored)
            {
            }
        }
        return r;
    }

    private static Patch convertWopnPatch(WopnBankReader.Patch wp)
    {
        Operator[] ops = new Operator[4];
        WopnBankReader.Operator[] wops = wp.operators();
        for (int l = 0; l < 4; l++)
        {
            WopnBankReader.Operator wo = wops[l];
            // DT1 occupies the same bit positions in WOPN dtfm as in OPM dt1mul (bits 6-4).
            // DT2 is absent from WOPN — leave as 0.
            ops[l] = new Operator(
                wo.dtfm(),             // dt1mul: DT1 (bits 6-4) + MUL (bits 3-0)
                wo.level(),            // tl
                wo.rsatk(),            // ksatk: KS (bits 7-6) + AR (bits 4-0)
                wo.amdecay1(),         // amd1r: AM-EN (bit 7) + D1R (bits 4-0)
                wo.decay2() & 0x1F,    // dt2d2r: DT2=0, D2R from WOPN decay2
                wo.susrel()            // d1lrr: D1L (bits 7-4) + RR (bits 3-0)
            );
        }
        return new Patch(
            wp.name(),
            wp.noteOffset(),
            wp.percussionKeyNumber(),
            wp.fbalg(),
            wp.lfosens(),
            ops
        );
    }

    /**
     * Get the melodic patch for a GM program number.
     *
     * @param program program number 0-127
     * @throws IllegalArgumentException if out of range or patch missing
     */
    public Patch melodicPatch(int program)
    {
        if (program < 0 || program >= 128)
            throw new IllegalArgumentException("Program must be 0-127, got " + program);
        Patch p = melodicPatches[program];
        if (p == null)
            throw new IllegalArgumentException("No melodic patch for program " + program);
        return p;
    }

    /**
     * Get the percussion patch for a GM note number.
     *
     * @param note MIDI note 0-127
     * @throws IllegalArgumentException if out of range or patch missing
     */
    public Patch percussionPatch(int note)
    {
        if (note < 0 || note >= 128)
            throw new IllegalArgumentException("Note must be 0-127, got " + note);
        Patch p = percussionPatches[note];
        if (p == null)
            throw new IllegalArgumentException("No percussion patch for note " + note);
        return p;
    }

    private void parse(byte[] data) throws IOException
    {
        if (data.length < HEADER_SIZE)
            throw new IOException("OPM bank too small: " + data.length + " bytes");

        for (int i = 0; i < MAGIC.length; i++)
            if (data[i] != MAGIC[i])
                throw new IOException("Invalid OPM bank magic");

        // version u8, nMelodic u16le, nPercussion u16le
        int nMelodic    = toUint16LE(data, 11);
        int nPercussion = toUint16LE(data, 13);

        int melodicOff    = HEADER_SIZE;
        int percussionOff = melodicOff + nMelodic * PATCH_BYTES;

        parseBlock(data, melodicOff,    nMelodic,    melodicPatches);
        parseBlock(data, percussionOff, nPercussion, percussionPatches);
    }

    private static void parseBlock(byte[] data, int blockOff, int count,
            Patch[] patches) throws IOException
    {
        for (int i = 0; i < count && i < patches.length; i++)
        {
            int off = blockOff + i * PATCH_BYTES;
            if (off + PATCH_BYTES > data.length)
                throw new IOException("Truncated OPM bank at patch " + i);

            String name      = parseName(data, off);
            int noteOffset   = (byte) data[off + 16]; // signed
            int percKey      = data[off + 17] & 0xFF;
            int fbalg        = data[off + 18] & 0xFF;
            int lfosens      = data[off + 19] & 0xFF;

            Operator[] ops = new Operator[4];
            for (int l = 0; l < 4; l++)
            {
                int opOff = off + OP_OFFSET + l * OP_SIZE;
                ops[l] = new Operator(
                    data[opOff]     & 0xFF, // dt1mul
                    data[opOff + 1] & 0xFF, // tl
                    data[opOff + 2] & 0xFF, // ksatk
                    data[opOff + 3] & 0xFF, // amd1r
                    data[opOff + 4] & 0xFF, // dt2d2r  ← DT2 bits 7-6, D2R bits 4-0
                    data[opOff + 5] & 0xFF  // d1lrr
                    // [6] = ssgeg (reserved for OPM), [7] = pad — both ignored
                );
            }
            patches[i] = new Patch(name, noteOffset, percKey, fbalg, lfosens, ops);
        }
    }

    private static String parseName(byte[] data, int offset)
    {
        int end = offset;
        while (end < offset + 16 && data[end] != 0)
            end++;
        return new String(data, offset, end - offset);
    }

    private static int toUint16LE(byte[] data, int offset)
    {
        return (data[offset] & 0xFF) | ((data[offset + 1] & 0xFF) << 8);
    }
}
