/*
 * Copyright (c) 2026, Park, Sungchul All rights reserved.
 *
 * This source code is licensed under the BSD-style license found in the LICENSE file in the root
 * directory of this source tree.
 */

package com.fupfin.midiraja.export.vgm;

import java.io.IOException;
import java.io.InputStream;
import java.io.UncheckedIOException;

/**
 * {@link ChipHandler} for YM2151 (OPM) — 7 melodic FM channels + 1 percussion FM channel.
 *
 * <p>
 * OPM differs from OPN in its note-addressing scheme: instead of fnum+block, it uses a
 * key-code (KC) byte where bits 6-4 are the octave (0-7) and bits 3-0 are a 4-bit note
 * index (skipping values 3, 7, 11 to match the 12-note scale). Key-on is written to
 * register 0x08 as {@code (opMask << 3) | ch}.
 *
 * <p>
 * OPM-native GM patches are loaded from {@code ext/opm_gm_bank/opm_gm.bin} via
 * {@link OpmBankReader}. Operator registers: DT1/MUL (0x40+), TL (0x60+), KS/AR (0x80+),
 * AM-EN/D1R (0xA0+), DT2/D2R (0xC0+), D1L/RR (0xE0+). Channel config (RL/FL/CON) is at 0x20+ch.
 * The {@code dt2d2r} field (bits 7-6 = DT2, bits 4-0 = D2R) is OPM-exclusive and absent from
 * WOPN2 format; {@code opm_gm.bin} carries non-zero DT2 values for brass/bell/metallic timbres.
 *
 * <p>
 * Slot 7 (channel 7) is reserved for percussion. MIDI channel 9 events use OPM percussion
 * patches played at the patch's {@code percKey} tuning note.
 */
final class Ym2151Handler implements ChipHandler
{
    private static final int SLOTS = 8;

    /**
     * Maps MIDI semitone (0-11) to OPM KC note nibble.
     * OPM skips codes 3, 7, 11 to fit 12 notes into the 4-bit space.
     * IMPORTANT: OPM's octave boundary is at C# (not C). C (semitone 0) is
     * encoded as code 0xE of the <em>previous</em> octave — see
     * {@link #noteToKc(int)} which subtracts 1 from the octave when semitone == 0.
     */
    private static final int[] NOTE_TO_KC = { 0xE, 0, 1, 2, 4, 5, 6, 8, 9, 0xA, 0xC, 0xD };
    //                                          C   C# D  D# E  F  F# G  G# A   A#  B

    /** Operator layout within a channel: slot order for reg offset per-operator. */
    private static final int[] OP_OFFSETS = { 0, 8, 16, 24 };

    /** Cached patch per slot for mid-note updatePitch/updateVolume. */
    private final OpmBankReader.Patch[] slotPatch = new OpmBankReader.Patch[SLOTS];

    private static final OpmBankReader OPM_BANK = loadOpmBank();

    /**
     * Loads the OPM GM bank from {@code /opm/opm_gm.bin} on the classpath
     * (bundled under {@code src/main/resources/opm/}, generated by
     * {@code scripts/gen_opm_bank.py}).
     */
    private static OpmBankReader loadOpmBank()
    {
        try (InputStream in = Ym2151Handler.class.getResourceAsStream("/opm/opm_gm.bin"))
        {
            if (in == null)
                throw new UncheckedIOException(new IOException(
                        "/opm/opm_gm.bin not found on classpath"));
            return OpmBankReader.load(in.readAllBytes());
        }
        catch (IOException e)
        {
            throw new UncheckedIOException(e);
        }
    }

    @Override
    public ChipType chipType()
    {
        return ChipType.YM2151;
    }

    @Override
    public int slotCount()
    {
        return SLOTS;
    }

    @Override
    public int percussionPriority()
    {
        return 2; // FM patch percussion
    }

    @Override
    public void initSilence(VgmWriter w)
    {
        // Key-off all 8 channels (opMask = 0, so bits 6-3 = 0)
        for (int ch = 0; ch < SLOTS; ch++)
            w.writeOpm(0x08, ch); // key-off: opMask=0 → no operators keyed on
    }

    @Override
    public void startNote(int localSlot, int note, int velocity, int program, VgmWriter w)
    {
        OpmBankReader.Patch patch = OPM_BANK.melodicPatch(program);
        slotPatch[localSlot] = patch;
        writePatch(localSlot, patch, w);
        writeKeyOn(localSlot, note + patch.noteOffset(), w);
    }

    @Override
    public void silenceSlot(int localSlot, VgmWriter w)
    {
        w.writeOpm(0x08, localSlot); // key-off: opMask=0
    }

    @Override
    public void updatePitch(int localSlot, int note, int pitchBend, int bendRangeSemitones,
            VgmWriter w)
    {
        OpmBankReader.Patch patch = slotPatch[localSlot];
        if (patch == null)
            return;
        double effNote = ChipHandler.bentNote(note + patch.noteOffset(), pitchBend,
                bendRangeSemitones);
        int baseNote = (int) Math.floor(effNote);
        int kc = noteToKc(baseNote);
        int kf = (int) ((effNote - baseNote) * 64) & 0x3F;
        w.writeOpm(0x28 + localSlot, kc);
        w.writeOpm(0x30 + localSlot, kf << 2); // KF in bits 7-2
    }

    @Override
    public void updateVolume(int localSlot, int velocity, VgmWriter w)
    {
        // OPM patches are optimised with TL written directly (no velocity scaling);
        // updateVolume is a no-op until the bank is re-generated with scaleTl applied.
    }

    /** Slot used for FM-patch percussion when YM2151 is the sole handler (no MSM6258). */
    private static final int PERC_SLOT = SLOTS - 1;

    @Override
    public void handlePercussion(int note, int velocity, VgmWriter w)
    {
        if (velocity == 0)
        {
            silenceSlot(PERC_SLOT, w);
            return;
        }
        OpmBankReader.Patch patch;
        try
        {
            patch = OPM_BANK.percussionPatch(note);
        }
        catch (IllegalArgumentException e)
        {
            return; // no percussion patch for this GM note
        }
        writePatch(PERC_SLOT, patch, w);
        int keyNote = patch.percKey() > 0 ? patch.percKey() : note;
        writeKeyOn(PERC_SLOT, keyNote + patch.noteOffset(), w);
    }

    private void writePatch(int slot, OpmBankReader.Patch patch, VgmWriter w)
    {
        int alg = patch.fbalg() & 0x07;
        int fb = (patch.fbalg() >> 3) & 0x07;

        // Channel config: RL=11 (stereo), FL (feedback), CON (algorithm)
        w.writeOpm(0x20 + slot, 0xC0 | (fb << 3) | alg);

        // LFO sensitivity (PMS bits 6-4, AMS bits 1-0)
        w.writeOpm(0x38 + slot, patch.lfosens() & 0x77);

        for (int l = 0; l < 4; l++)
        {
            OpmBankReader.Operator op = patch.operators()[l];
            int regOff = OP_OFFSETS[l] + slot;

            // DT1/MUL: bits 6-4 = DT1, bits 3-0 = MUL
            w.writeOpm(0x40 + regOff, op.dt1mul());
            // TL: written directly — DE optimised patches with TL calibrated for direct writes
            w.writeOpm(0x60 + regOff, op.tl() & 0x7F);
            // KS/AR: bits 7-6 = KS, bits 4-0 = AR
            w.writeOpm(0x80 + regOff, op.ksatk());
            // AM-EN/D1R: bit 7 = AM-EN, bits 4-0 = D1R
            w.writeOpm(0xA0 + regOff, op.amd1r());
            // DT2/D2R: bits 7-6 = DT2 (OPM-exclusive), bits 4-0 = D2R
            w.writeOpm(0xC0 + regOff, op.dt2d2r());
            // D1L/RR: bits 7-4 = D1L, bits 3-0 = RR
            w.writeOpm(0xE0 + regOff, op.d1lrr());
        }
    }

    /**
     * Converts a MIDI note number to an OPM KC byte.
     *
     * <p>OPM's octave boundary falls at C# (not C): C is the <em>last</em> note
     * of the previous octave (code 0xE), while C# starts the next octave (code
     * 0x0). The octave is therefore decremented by one for semitone 0 (C).
     */
    private static int noteToKc(int note)
    {
        int semitone = note % 12;
        int octave = note / 12 - 1 - (semitone == 0 ? 1 : 0);
        octave = Math.clamp(octave, 0, 7);
        return (octave << 4) | NOTE_TO_KC[semitone];
    }

    private void writeKeyOn(int slot, int note, VgmWriter w)
    {
        int kc = noteToKc(note);
        w.writeOpm(0x28 + slot, kc);        // KC: octave + note code
        w.writeOpm(0x30 + slot, 0);          // KF: no fine pitch offset
        w.writeOpm(0x08, (0xF << 3) | slot); // key-on: all 4 operators
    }

}
