#!/usr/bin/env python3
"""
decode_drums.py — Decode drum sample .bin files to WAV for listening / quality verification.

Decodes both RF5C68 (sign-magnitude PCM) and MSM6258 (OKI ADPCM) drum samples
generated by extract_drum_samples.py, and writes WAV files to /tmp/.

Usage (from project root):
    python3 scripts/decode_drums.py

Output:
    /tmp/rf5c68_{i}_{name}.wav    16 000 Hz mono 16-bit PCM
    /tmp/msm6258_{i}_{name}.wav   15 625 Hz mono 16-bit PCM
"""

import os
import struct
import wave
import numpy as np

RESOURCE_DIR = os.path.join(
    os.path.dirname(__file__), "..",
    "src", "main", "resources", "com", "fupfin", "midiraja", "export", "vgm",
)

DRUM_NAMES = ["bass_drum", "snare", "cymbal", "closed_hh", "tom", "rim_shot", "open_hh"]


# ── RF5C68 decoder ────────────────────────────────────────────────────────────

def decode_rf5c68(data, rate=16_000):
    """Sign-magnitude bytes → int16 PCM.  0xFF terminates the sample."""
    out = []
    for b in data:
        if b == 0xFF:
            break                       # end-of-sample marker
        mag = (b & 0x7F) / 0x7E        # normalise magnitude to [0, 1]
        s = mag if (b & 0x80) else -mag
        out.append(int(s * 32767))
    return np.array(out, dtype=np.int16), rate


# ── OKI ADPCM (MSM6258) decoder ───────────────────────────────────────────────

def decode_msm6258(data, rate=15_625):
    """OKI ADPCM 4-bit packed (low nibble first) → int16 PCM.

    Algorithm matches okim6258.c from libvgm / MAME.
    """
    STEP_VAL = [int(16.0 * (1.1 ** i)) for i in range(49)]
    IDX_SHIFT = [-1, -1, -1, -1, 2, 4, 6, 8]

    diff_lookup = [0] * (49 * 16)
    for step in range(49):
        sv = STEP_VAL[step]
        for nibble in range(16):
            d = sv >> 3
            if nibble & 1: d += sv >> 2
            if nibble & 2: d += sv >> 1
            if nibble & 4: d += sv
            if nibble & 8: d = -d
            diff_lookup[step * 16 + nibble] = d

    out = []
    sig, step = -2, 0
    for byte in data:
        for shift in (0, 4):
            nibble = (byte >> shift) & 0x0F
            diff = diff_lookup[step * 16 + nibble]
            sig = max(-2048, min(2047, ((diff << 8) + (sig * 245)) >> 8))
            step = max(0, min(48, step + IDX_SHIFT[nibble & 7]))
            out.append(sig)

    # Scale 12-bit [-2048, 2047] to 16-bit
    arr = np.array(out, dtype=np.float32) / 2048.0 * 32767
    return arr.astype(np.int16), rate


# ── WAV writer ────────────────────────────────────────────────────────────────

def write_wav(path, samples, rate):
    with wave.open(path, "w") as w:
        w.setnchannels(1)
        w.setsampwidth(2)
        w.setframerate(rate)
        w.writeframes(samples.tobytes())


# ── Main ──────────────────────────────────────────────────────────────────────

def main():
    for i, name in enumerate(DRUM_NAMES):
        rf_path  = os.path.join(RESOURCE_DIR, f"rf5c68_drum_{i}.bin")
        msm_path = os.path.join(RESOURCE_DIR, f"msm6258_drum_{i}.bin")

        rf_data  = open(rf_path,  "rb").read()
        msm_data = open(msm_path, "rb").read()

        rf_pcm,  rf_rate  = decode_rf5c68(rf_data)
        msm_pcm, msm_rate = decode_msm6258(msm_data)

        rf_peak  = int(np.max(np.abs(rf_pcm.astype(np.int32))))  if len(rf_pcm)  else 0
        msm_peak = int(np.max(np.abs(msm_pcm.astype(np.int32)))) if len(msm_pcm) else 0

        print(f"[{i}] {name}")
        print(f"    RF5C68  : {len(rf_data):5d} bytes  {len(rf_pcm):5d} samples  peak={rf_peak}/32767")
        print(f"    MSM6258 : {len(msm_data):5d} bytes  {len(msm_pcm):5d} samples  peak={msm_peak}/32767")

        write_wav(f"/tmp/rf5c68_{i}_{name}.wav",  rf_pcm,  rf_rate)
        write_wav(f"/tmp/msm6258_{i}_{name}.wav", msm_pcm, msm_rate)

    print("\nWAV files written to /tmp/")


if __name__ == "__main__":
    main()
